/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'James' at '8/15/17 3:34 PM' with Gradle 2.9
 *
 * @author James, @date 8/15/17 3:34 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
